// Solicitando lista total
GET http://localhost:3000/student

// Buscando primeiro usuario
####
GET http://localhost:3000/student/1
// Buscando segundo usuario
####
GET http://localhost:3000/student/2
// Buscando terceiro usuario
####
GET http://localhost:3000/student/3
// Retorna usuário não encontrado

####
//Mostra conteúdo dentro de assunto
GET http:localhost:3000/assunto
####
GET http://localhost:3000/student/55
